#!/bin/bash
curl -s --user 'api:key-0fcbdb08fd52c5216420312b59c679a4' \
    https://api.mailgun.net/v3/mg.focusleague.com/messages \
    -F from='FOCUS League <support@focusleague.com>' \
    -F to='announce@mg.focusleague.com' \
    -F subject='FOCUS League - 2016 Summer Schedule Update' \
    -F html='<schedule-update.html' \
    -F o:tag='schedule-update' \
    -F o:tracking=true \
    -F o:tracking-clicks=true \
    -F o:tracking-opens=true
