#!/bin/bash
curl -s --user 'api:key-0fcbdb08fd52c5216420312b59c679a4' \
    https://api.mailgun.net/v3/mg.focusleague.com/messages \
    -F from='Stephen Haff <shaff315@gmail.com>' \
    -F to='announce@mg.focusleague.com' \
    -F subject='FOCUS League BBQ - TODAY, 2p at Memorial Park' \
    -F html='<bbq-announce.html' \
    -F o:tag='social' \
    -F o:tracking=true \
    -F o:tracking-clicks=true \
    -F o:tracking-opens=true
