#!/bin/bash
curl -s --user 'api:key-0fcbdb08fd52c5216420312b59c679a4' \
    https://api.mailgun.net/v3/mg.focusleague.com/messages \
    -F from='FOCUS League <support@focusleague.com>' \
    -F to='announce@mg.focusleague.com' \
    -F subject='Sign-up for FOCUS League Cycle 2016-05 is now open!' \
    -F html='<Cycle2016-05SignupOpenAnnouncement.html' \
    -F o:tag='signup-open' \
    -F o:tracking=true \
    -F o:tracking-clicks=true \
    -F o:tracking-opens=true
